Repository besteon/Ironmon-Tracker, pull requests merged in 2022-07, with the labels that each got.

#99 Fixing visual issue with using special character
  README.md
  ironmon_tracker/Drawing.lua
  ironmon_tracker/Options.lua
Labels: Bizhawk bug

#125 Transform bug fix
  ironmon_tracker/Program.lua
  ironmon_tracker/TrackerScreen.lua
Labels: Bug, Move Tracking

#133 fix ability blanking out on evolution
  ironmon_tracker/Tracker.lua
Labels: Bug, Ability Tracking
