Repository besteon/Ironmon-Tracker, pull requests merged in 2022-10, with the labels that each got.

#248 Iconsets: Author credits and periodic icon change
  ironmon_tracker/Options.lua
  ironmon_tracker/screens/SetupScreen.lua
Labels: Enhancement

#258 Feature: Clicking on number of Attempts now allows user to edit the counter
  Ironmon-Tracker.lua
  ironmon_tracker/Constants.lua
  ironmon_tracker/GameSettings.lua
  ironmon_tracker/Theme.lua
  ironmon_tracker/Tracker.lua
  ironmon_tracker/screens/StartupScreen.lua
  ironmon_tracker/screens/TrackedDataScreen.lua
Labels: Enhancement

#260 Feature: Random Ball Picker
  Ironmon-Tracker.lua
  ironmon_tracker/Constants.lua
  ironmon_tracker/Drawing.lua
  ironmon_tracker/Options.lua
  ironmon_tracker/data/RouteData.lua
  ironmon_tracker/screens/GameOptionsScreen.lua
  ironmon_tracker/screens/InfoScreen.lua
  ironmon_tracker/screens/NavigationMenu.lua
  ironmon_tracker/screens/QuickloadScreen.lua
  ironmon_tracker/screens/StartupScreen.lua
  ironmon_tracker/screens/TrackerScreen.lua
Labels: Feature Request

#266 GameSettings cleanup
  Ironmon-Tracker.lua
  ironmon_tracker/GameSettings.lua
Labels: Enhancement

#268 Last seen level of encountered Pokemon now tracked
  ironmon_tracker/Battle.lua
  ironmon_tracker/Tracker.lua
  ironmon_tracker/screens/TrackerScreen.lua
Labels: Feature Request

#275 Feature: Text shadow option and preset thumbnail previews
  Ironmon-Tracker.lua
  ThemePresets.txt
  ironmon_tracker/Drawing.lua
  ironmon_tracker/Theme.lua
  ironmon_tracker/screens/InfoScreen.lua
  ironmon_tracker/screens/TrackerScreen.lua
Labels: Enhancement, Feature Request

#276 A more robust Theme Manager
  ThemePresets.txt
  ironmon_tracker/Constants.lua
  ironmon_tracker/Drawing.lua
  ironmon_tracker/Theme.lua
  ironmon_tracker/Utils.lua
  ironmon_tracker/screens/NavigationMenu.lua
Labels: Enhancement
