Repository besteon/Ironmon-Tracker, pull requests merged in 2022-08, with the labels that each got.

#137 Update currently supported games
  README.md
  README.txt
  ironmon_tracker/GameSettings.lua
Labels: Documentation

#143 Auto-ability tracking
  ironmon_tracker/GameSettings.lua
  ironmon_tracker/Program.lua
Labels: Enhancement, Ability Tracking

#145 Carousel Feature, Full Route Data, and Last Damage Tracking
  .gitignore
  Ironmon-Tracker.lua
  Settings.ini
  ironmon_tracker/Constants.lua
  ironmon_tracker/Drawing.lua
  ironmon_tracker/GameSettings.lua
  ironmon_tracker/InfoScreen.lua
  ironmon_tracker/Input.lua
  ironmon_tracker/Options.lua
  ironmon_tracker/Program.lua
  ironmon_tracker/Theme.lua
  ironmon_tracker/Tracker.lua
  ironmon_tracker/TrackerScreen.lua
  ironmon_tracker/Utils.lua
  ironmon_tracker/data/MiscData.lua
  ironmon_tracker/data/MoveData.lua
  ironmon_tracker/data/PokemonData.lua
  ironmon_tracker/data/RouteData.lua
  ironmon_tracker/images/status/BRN.png
  ironmon_tracker/images/status/FRZ.png
  ironmon_tracker/images/status/PAR.png
  ironmon_tracker/images/status/PSN.png
  ironmon_tracker/images/status/SLP.png
Labels: Enhancement

#146 New Navigation Menu and bonus features
  Ironmon-Tracker.lua
  ironmon_tracker/Constants.lua
  ironmon_tracker/Drawing.lua
  ironmon_tracker/InfoScreen.lua
  ironmon_tracker/Input.lua
  ironmon_tracker/Options.lua
  ironmon_tracker/Program.lua
  ironmon_tracker/Theme.lua
  ironmon_tracker/TrackerScreen.lua
  ironmon_tracker/Utils.lua
  ironmon_tracker/data/RouteData.lua
  ironmon_tracker/screens/GameOptionsScreen.lua
  ironmon_tracker/screens/InfoScreen.lua
  ironmon_tracker/screens/NavigationMenu.lua
  ironmon_tracker/screens/SetupScreen.lua
  ironmon_tracker/screens/TrackedDataScreen.lua
  ironmon_tracker/screens/TrackerScreen.lua
Labels: Enhancement

#147 Automatic Weather Ball Updates
  ironmon_tracker/GameSettings.lua
  ironmon_tracker/Utils.lua
  ironmon_tracker/screens/InfoScreen.lua
  ironmon_tracker/screens/TrackerScreen.lua
Labels: Enhancement, Move Tracking

#148 Last damage warning
  ironmon_tracker/screens/TrackerScreen.lua
Labels: Enhancement

#153 Fixing infinite loop crash and blinking carousel
  README.md
  ironmon_tracker/Input.lua
  ironmon_tracker/Memory.lua
  ironmon_tracker/Program.lua
  ironmon_tracker/Tracker.lua
  ironmon_tracker/data/MoveData.lua
  ironmon_tracker/screens/TrackerScreen.lua
Labels: Bug

#160 Restore fishing law
  ironmon_tracker/Constants.lua
  ironmon_tracker/Program.lua
  ironmon_tracker/Tracker.lua
  ironmon_tracker/Utils.lua
Labels: Enhancement

#159 Improved version/file checks
  Ironmon-Tracker.lua
  ironmon_tracker/Utils.lua
Labels: Enhancement

#188 Replace route info MORE button with back/forward cycle buttons
  ironmon_tracker/data/RouteData.lua
  ironmon_tracker/screens/InfoScreen.lua
Labels: Enhancement, Encounter Tracking

#196 Bill's Island Adventure! (Sevii Isles Data)
  ironmon_tracker/Battle.lua
  ironmon_tracker/Constants.lua
  ironmon_tracker/GameSettings.lua
  ironmon_tracker/Tracker.lua
  ironmon_tracker/data/RouteData.lua
  ironmon_tracker/screens/TrackerScreen.lua
Labels: Enhancement, Encounter Tracking

#205 Feature: Adding option to disable carousel on the main Tracker screen
  ironmon_tracker/Constants.lua
  ironmon_tracker/Options.lua
  ironmon_tracker/screens/SetupScreen.lua
  ironmon_tracker/screens/TrackerScreen.lua
Labels: Enhancement
